### ISSUE TITLE
add excel file to populate admin table

### ISSUE THREAD

**Issue by richa-gupta-1998** [richa-gupta-1998/AmazonClone#7]
Provide option to admin, to add an excel file to add Book name, price, author, Quantity. Prompt user to copy paste excel path which has book database. when user clicks on add data populate the admin table.

**Description**
This java program converts excel workbook into MySQL table inside the specific database by taking excel path as a input from user. For this we need JAR file to convert excel data's into SQL table. I have attached that file as well

**Comment by Dharshini-R53** [comment]
@richa-gupta-1998 
Add price column to the table.

**Comment by Dharshini-R53** [comment]
catch (Exception e) {
            e.printStackTrace();
        }
 Avoid use of letters like e
 Ensure naming conventions
